module Pages.AboutMe exposing (view)

import Bootstrap.Grid as Grid
import Html exposing (..)
import Html.Attributes exposing (..)


view : Html msg
view =
    div [ class "main-content" ]
        [ Grid.container
            [ Grid.row
                [ div [ class "main-title col text-secondary bg-warning" ]
                    [ header []
                        [ h1 [ class "text-info" ]
                            [ text "About Me" ]
                        ]
                    ]
                ]
            , Grid.row
                [ Grid.column []
                    [ section []
                        [ h2 []
                            [ text "Bio" ]
                        , section []
                            [ h3 []
                                [ text "Early Life" ]
                            , p []
                                [ text "I was in a military family and moved around a ton. I also got born and stuff." ]
                            ]
                        , section []
                            [ h3 []
                                [ text "Recent" ]
                            , p []
                                [ text "Spent the summer doing web programming making websites of the web variety for Wiegand Glas in Germany." ]
                            ]
                        ]
                    , section []
                        [ h2 []
                            [ text "Work Experience" ]
                        , div [ class "table-container" ]
                            [ table [ class "table" ]
                                [ thead []
                                    [ tr []
                                        [ th []
                                            [ text "Position" ]
                                        , th []
                                            [ text "Employer" ]
                                        , th []
                                            [ text "Start Year" ]
                                        , th []
                                            [ text "End Year" ]
                                        ]
                                    ]
                                , tr []
                                    [ td []
                                        [ text "Lifeguard" ]
                                    , td []
                                        [ text "Oro Valley" ]
                                    , td []
                                        [ text "2015" ]
                                    , td []
                                        [ text "2017" ]
                                    ]
                                , tr []
                                    [ td []
                                        [ text "Web Programming Intern" ]
                                    , td []
                                        [ text "Wiegand Glas" ]
                                    , td []
                                        [ text "2018" ]
                                    , td []
                                        [ text "2018" ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                , Grid.column []
                    [ section []
                        [ h2 []
                            [ text "Accomplishments" ]
                        , ul []
                            [ li []
                                [ text "Dean's List" ]
                            , li []
                                [ text "NAU Honors College" ]
                            , li []
                                [ text "Other Cool Stuff" ]
                            ]
                        ]
                    , section []
                        [ h2 []
                            [ text "Hobbies & Interests" ]
                        , ul []
                            [ li []
                                [ text "Sword Fighting" ]
                            , li []
                                [ text "Karate" ]
                            , li []
                                [ text "Swimming" ]
                            , li []
                                [ text "Biking" ]
                            , li []
                                [ text "Not running" ]
                            , li []
                                [ text "Full Stack Web Development" ]
                            , li []
                                [ text "Other cool stuff" ]
                            ]
                        ]
                    ]
                ]
            , Grid.row
                [ Grid.column []
                    [ footer []
                        [ p [ id "copyright" ]
                            [ text "© Jared Weinberger the Magnificent" ]
                        ]
                    ]
                ]
            ]
        ]
